Modify Makefiles, add get_deps script

diff --git a/core/Makefile.module b/core/Makefile.module
--- a/core/Makefile.module
+++ b/core/Makefile.module
@@ -18,19 +18,22 @@
 NAME       := $(shell a=$$(pwd); echo $${a\#\#*/})
 STATIC_LIB := $(NAME).a
 OBJECTS    := $(patsubst %.cpp, %.o, $(SOURCES))
+MODDIR     ?= ..
 
 # extract #include statements from SOURCES and HEADERS:
 HDEPS := $(shell [ "$(SOURCES)$(HEADERS)" = "" ] ||\
-          sed -rne 's|^\#include +"([^/]*/[^/]*)".*|../\1|p'\
+          sed -rne 's|^\#include +"([^/]*/[^/]*)".*|$(MODDIR)/\1|p'\
           $(SOURCES) $(HEADERS) | sort -u)
 
-# module dirs:
-MDEPS := $(shell for i in $(HDEPS); do echo $${i%/*}; done | sort -u)
+## module dirs:
+## old code (without get_dep script)
+#MDEPS := $(shell for i in $(HDEPS); do echo $${i%/*}; done | sort -u)
+
+## module dirs:
+MDEPS := $(shell $(MODDIR)/get_deps $(MODDIR) $(NAME))
 
 # a-files
-ADEPS := $(shell for i in $(MDEPS); do echo $$i/$${i\#*/}.a; done)
-
-override CPPFLAGS += -I..
+ADEPS := $(shell for i in $(MDEPS); do echo $(MODDIR)/$$i/$${i\#*/}.a; done)
 
 ALL_TESTS   := $(SIMPLE_TESTS) $(SCRIPT_TESTS)
 SIMPLE_TEST_PROGS := $(patsubst %, %.test, $(SIMPLE_TESTS))
@@ -45,49 +48,55 @@ $(SCRIPT_TEST_RES): TEST_DEP := %.test.script
 $(SIMPLE_TEST_RES): TEST_CMD = ./$< && > $<.passed
 $(SCRIPT_TEST_RES): TEST_CMD = ./$<.script && > $<.passed
 
+override CXXFLAGS += $(shell pkg-config --cflags '$(PKG_CONFIG)')
+override LDLIBS   += $(shell pkg-config --libs '$(PKG_CONFIG)')
+override CPPFLAGS += -I$(MODDIR)
 
 ######################################################
 # building a module: print info, make dependencies,
 # build static library, build and run tests
-all: make_deps print_info $(STATIC_LIB) $(ALL_TEST_RES)
+all: make_deps $(STATIC_LIB) $(ALL_TEST_RES)
+nodep: $(STATIC_LIB) $(ALL_TEST_RES)
 
 ######################################################
-# dependencies
-.INTERMEDIATE.: %.lock
-make_deps:
-	@if [ -f $ $(NAME).lock ]; then\
-	  echo "### error: infinit dependency loop or outdated lock file for $(NAME) ###";\
-	  rm -f $(NAME).lock;\
-	  false;\
-	fi
-	@touch $(NAME).lock
-	@echo "###########################"
-	@echo "## Building dependencies for $(NAME): $(MDEPS)"
-	@for i in $(MDEPS); do \
-	  $(MAKE) -C $$i || (rm -f $(NAME).lock && false);\
-	done
-	@rm -f $(NAME).lock
+## dependencies
 
-%.lock:
-	touch $@
+## old code (without get_deps script): works fine,
+## but visits modules more then once
+# make_deps:
+# 	@if [ -f $ $(NAME).lock ]; then\
+# 	  echo "### error: infinit dependency loop or outdated lock file for $(NAME) ###";\
+# 	  rm -f $(NAME).lock;\
+# 	  false;\
+# 	fi
+# 	@touch $(NAME).lock
+# 	@echo "###########################"
+# 	@echo "## Building dependencies for $(NAME): $(MDEPS)"
+# 	@for i in $(MDEPS); do \
+# 	  $(MAKE) -C $$i || (rm -f $(NAME).lock && false);\
+# 	done
+# 	@rm -f $(NAME).lock
+
+make_deps:
+	@echo "Dependencies for $(NAME): [$(MDEPS)]"
+	@for i in $(MDEPS); do $(MAKE) -C $(MODDIR)/$$i nodep; done
 
 ######################################################
 # static library
 $(OBJECTS): $(HEADERS) $(HDEPS)
 
-$(STATIC_LIB): $(OBJECTS) $(ADEPS)
-	@echo "## Building static library for $(NAME)"
-	ar rs $(STATIC_LIB) $(OBJECTS)
+$(STATIC_LIB): $(OBJECTS)
+	@echo "## Building static library for $(NAME):"
+	ar rs $@ $+
 
 ######################################################
 # tests
 
 %.test: %.test.cpp $(OBJECTS) $(ADEPS) $(HDEPS) $(HEADERS)
-	@echo "## Building test script $@"
 	$(CXX) $(CPPFLAGS) $(LDFLAGS) $< $(OBJECTS) $(ADEPS) $(LDLIBS) -o $@
 
 %.test.passed: %.test $(TEST_DEP)
-	@echo "## Running test command $@"
+	@echo "## Running test:"
 	$(TEST_CMD)
 
 ######################################################
